name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $username -p $password


    - name: Build and push Docker images
    # You may pin to the exact commit or the version.
    # uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
      uses: docker/build-push-action@v6.7.0
      with:
        # Path to the Dockerfile
        file: ecommerce-project
        # List of tags
        tags: latest
        # Sets the target stage to build
        target: ecommerce-app
              
